import { forwardRef } from "react";
import { Flame } from "lucide-react";
import type { Platform, RoastResult } from "@/lib/validation";

type ShareCardProps = {
  platform: Platform;
  result: RoastResult;
};

function compact(text: string, maxLength: number) {
  if (text.length <= maxLength) {
    return text;
  }

  return `${text.slice(0, maxLength - 1).trim()}...`;
}

export const ShareCard = forwardRef<HTMLDivElement, ShareCardProps>(
  function ShareCard({ platform, result }, ref) {
    return (
      <div
        ref={ref}
        className="mx-auto flex aspect-[9/16] w-full max-w-[360px] flex-col overflow-hidden rounded-[2rem] border border-white bg-[#fff7ed] p-5 text-slate-950 shadow-2xl shadow-orange-100"
      >
        <div className="absolute -z-10" />
        <div className="flex items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="flex size-11 items-center justify-center rounded-2xl bg-slate-950 text-white">
              <Flame aria-hidden="true" className="size-5" />
            </div>
            <div>
              <p className="text-base font-black tracking-tight">
                Roast My Profile
              </p>
              <p className="text-[10px] font-black uppercase tracking-[0.2em] text-pink-600">
                {platform}
              </p>
            </div>
          </div>
        </div>

        <div className="mt-5 rounded-[1.5rem] bg-gradient-to-br from-fuchsia-600 via-pink-500 to-orange-400 p-1">
          <div className="rounded-[1.25rem] bg-white p-4">
            <p className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-600">
              Your Roast
            </p>
            <p className="story-card-text story-card-text-4 mt-2 text-base font-black leading-6 text-slate-950">
              {compact(result.roast, 230)}
            </p>
          </div>
        </div>

        <div className="mt-4 flex-1 rounded-[1.5rem] bg-white/80 p-4 shadow-inner">
          <p className="text-[10px] font-black uppercase tracking-[0.2em] text-fuchsia-700">
            Better Bio
          </p>
          <p className="story-card-text story-card-text-5 mt-2 text-sm font-semibold leading-6 text-slate-800">
            {compact(result.betterBio, 300)}
          </p>
        </div>

        <div className="mt-4 rounded-2xl border border-orange-100 bg-white/70 p-3">
          <p className="text-xs font-black leading-5 text-slate-700">
            {compact(result.shareCaption, 130)}
          </p>
        </div>

        <p className="mt-4 text-center text-[11px] font-black uppercase tracking-[0.18em] text-slate-500">
          Generated by Roast My Profile
        </p>
      </div>
    );
  },
);
