"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import { toPng } from "html-to-image";
import { Hero } from "@/components/Hero";
import { ProfileForm } from "@/components/ProfileForm";
import type { ExampleBio } from "@/components/ExampleBios";
import { Results } from "@/components/Results";
import { generateRoast, GENERATION_FALLBACK_ERROR } from "@/lib/api";
import {
  validateGenerateRoastInput,
  type Platform,
  type RoastResult,
  type Tone,
} from "@/lib/validation";

const LOADING_MESSAGES = [
  "Preparing emotional damage...",
  "Checking bio crimes...",
  "Finding your upgrade arc...",
];

function wait(milliseconds: number) {
  return new Promise((resolve) => window.setTimeout(resolve, milliseconds));
}

function filenameFor(platform: Platform) {
  return `roast-my-profile-${platform.toLowerCase().replace(/[^a-z0-9]+/g, "-")}.png`;
}

export default function RoastApp() {
  const [profileText, setProfileText] = useState("");
  const [platform, setPlatform] = useState<Platform>("Instagram");
  const [tone, setTone] = useState<Tone>("Savage but funny");
  const [result, setResult] = useState<RoastResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [downloadError, setDownloadError] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  const [loadingIndex, setLoadingIndex] = useState(0);

  const formRef = useRef<HTMLDivElement>(null);
  const resultsRef = useRef<HTMLDivElement>(null);
  const shareCardRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!isGenerating) {
      return;
    }

    const timer = window.setInterval(() => {
      setLoadingIndex((index) => (index + 1) % LOADING_MESSAGES.length);
    }, 650);

    return () => window.clearInterval(timer);
  }, [isGenerating]);

  function scrollToForm() {
    formRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
  }

  function handleExampleSelect(example: ExampleBio) {
    setProfileText(example.text);
    setPlatform(example.platform);
    setError(null);
    window.setTimeout(scrollToForm, 50);
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    if (isGenerating) {
      return;
    }

    const validation = validateGenerateRoastInput({
      profileText,
      platform,
      tone,
    });

    if (!validation.success) {
      setError(validation.message);
      setResult(null);
      return;
    }

    setError(null);
    setDownloadError(null);
    setLoadingIndex(0);
    setIsGenerating(true);

    try {
      const [nextResult] = await Promise.all([
        generateRoast(validation.data),
        wait(1500),
      ]);

      setResult(nextResult);
      window.setTimeout(() => {
        resultsRef.current?.scrollIntoView({
          behavior: "smooth",
          block: "start",
        });
      }, 80);
    } catch (caughtError) {
      setResult(null);
      setError(
        caughtError instanceof Error
          ? caughtError.message
          : GENERATION_FALLBACK_ERROR,
      );
    } finally {
      setIsGenerating(false);
    }
  }

  async function handleDownload() {
    if (!shareCardRef.current || isDownloading) {
      return;
    }

    setDownloadError(null);
    setIsDownloading(true);

    try {
      await document.fonts?.ready;

      const dataUrl = await toPng(shareCardRef.current, {
        cacheBust: true,
        pixelRatio: Math.max(2, Math.min(window.devicePixelRatio || 2, 3)),
        backgroundColor: "#fff7ed",
      });

      const link = document.createElement("a");
      link.href = dataUrl;
      link.download = filenameFor(platform);
      link.click();
    } catch {
      setDownloadError("Card download failed. Please try again.");
    } finally {
      setIsDownloading(false);
    }
  }

  function handleShareOnX() {
    if (!result) {
      return;
    }

    const text = encodeURIComponent(
      `${result.shareCaption}\n\nGenerated by Roast My Profile`,
    );
    window.open(
      `https://twitter.com/intent/tweet?text=${text}`,
      "_blank",
      "noopener,noreferrer",
    );
  }

  function handleTryAgain() {
    setResult(null);
    setError(null);
    setDownloadError(null);
    window.setTimeout(scrollToForm, 50);
  }

  return (
    <main className="min-h-screen overflow-hidden">
      <Hero onStart={scrollToForm} />
      <div ref={formRef}>
        <ProfileForm
          error={error}
          isGenerating={isGenerating}
          loadingMessage={LOADING_MESSAGES[loadingIndex]}
          platform={platform}
          profileText={profileText}
          tone={tone}
          onExampleSelect={handleExampleSelect}
          onPlatformChange={setPlatform}
          onProfileTextChange={setProfileText}
          onSubmit={handleSubmit}
          onToneChange={setTone}
        />
      </div>

      {result ? (
        <div ref={resultsRef}>
          <Results
            downloadError={downloadError}
            isDownloading={isDownloading}
            platform={platform}
            result={result}
            shareCardRef={shareCardRef}
            onDownload={handleDownload}
            onShareOnX={handleShareOnX}
            onTryAgain={handleTryAgain}
          />
        </div>
      ) : null}
    </main>
  );
}
